how to create an **array** to manage data. After that, you will learn how
to use the Python library **NumPy** to support advanced calculation for your
dataset.
___
### Python List
The basic structure in Python that is used to handle a group of data of the
same type is called **“Python list”**. List is similar to *array* in other programming
languages, but with **more flexibility**. 

Python list is **resizable**, and the values
inside a Python list is **not** necessary to be the _same data type_.

In [20]:
a = [1,2,3]
a[2] = 5
print(a)

[1, 2, 5]


In [1]:
# resizeable

a = [1,2,3]
print(a)
a.extend([0]*5)
print(a)

[1, 2, 3]
[1, 2, 3, 0, 0, 0, 0, 0]


In [6]:
# using append

size = []
print(size)
size.append('S')
size.append('M')
size.append('L')
size.append('XL')
print(size)

[]
['S', 'M', 'L', 'XL']


In [8]:
# to print without new line

for i in size:
    print(i, end=" ")

S M L XL 

In [9]:
#  if there are multiple Python list in the loop

waist_inch = [28, 30, 32, 34]
for i in size, waist_inch:
    print(i)

['S', 'M', 'L', 'XL']
[28, 30, 32, 34]


In [10]:
# quickly initialize values for a Python list

waist_cm = [0 for x in range(4)]
print(waist_cm)

[0, 0, 0, 0]


In [11]:
# change the number ”0” to other number
# in this case we convert from inch (in waist_inch) to cm

for i in range(len(waist_inch)):
    waist_cm[i] = waist_inch[i]*2.54
print(waist_cm)

[71.12, 76.2, 81.28, 86.36]


In [12]:
# same thing
hip_inch = [37,39,42,45]
hip_cm = [hip_inch[i]*2.54 for i in range(len(hip_inch))]
print(hip_cm)

[93.98, 99.06, 106.68, 114.3]


In [19]:
size = [['S', 'M', 'L', 'XL'],[28,30,32,34], [37,39,42,45],[],[]]
for i in range(len(size[0])):
    size[3].append(size[1][i]*2.54)
    size[4].append(size[2][i]*2.54)
print(*size, sep="\n")  # sep is used to print new line to each list inside (that's all lol)
# without sep
print('\n',size)

['S', 'M', 'L', 'XL']
[28, 30, 32, 34]
[37, 39, 42, 45]
[71.12, 76.2, 81.28, 86.36]
[93.98, 99.06, 106.68, 114.3]

 [['S', 'M', 'L', 'XL'], [28, 30, 32, 34], [37, 39, 42, 45], [71.12, 76.2, 81.28, 86.36], [93.98, 99.06, 106.68, 114.3]]


### NumPy
NumPy is one of the widely used Python library. Similar to Python list, the
library supports the creation of array. However, NumPy offers better memory
management and faster computational speed. Moreover, NumPy offers provides
advanced computational tools, especially for Matrix calculation. Then, NumPy
is a fundamental package for scientific computing with Python.

In [22]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(4,5,6,7),(8,9,10,11)])
print(a)
print(b)

[1 2 3]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
b = np.array(a)
print(a*3)
print(b*3)
print(a+3)
print(b+3)

[3 6 9]
[3 6 9]
[4 5 6]
[4 5 6]


In [23]:
a = np.arange(15)
print(a,'\n')
print(a.reshape(3, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
a = np.zeros((3,3))
print(a,'\n')
b = np.ones((6,6))
print(b,'\n')
c = np.empty((4,5))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307
  1.33508845e-306]
 [1.33511969e-306 6.23037996e-307 6.23053954e-307 9.34609790e-307
  8.45593934e-307]
 [9.34600963e-307 1.86921143e-306 6.23061763e-307 1.78021527e-306
  6.23055651e-307]
 [1.11261434e-306 9.34609790e-307 1.69120688e-306 1.69119330e-306
  8.34451079e-308]]


In [37]:
print(a.size, a.shape, a.ndim, a.dtype, sep=" | ")
print(b.size, b.shape, b.ndim, b.dtype, sep=" | ")
print(c.size, c.shape, c.ndim, c.dtype, sep=" | ")

9 | (3, 3) | 2 | float64
36 | (6, 6) | 2 | float64
20 | (4, 5) | 2 | float64


In [38]:
a = np.arange(4)
b = np.arange(8).reshape(2,4)
c = np.ones(4)
print(a)
print(b)
print(c)
print()
print(a+c)
print(b-c)
print(a+5)

[0 1 2 3]
[[0 1 2 3]
 [4 5 6 7]]
[1. 1. 1. 1.]

[1. 2. 3. 4.]
[[-1.  0.  1.  2.]
 [ 3.  4.  5.  6.]]
[5 6 7 8]


In [47]:
a = np.arange(4)
b = np.arange(8).reshape(2,4)
print(b)
print('Sum of all a is ',a.sum())
print('how axis=0 works: ',b.sum(axis=0))
print('min of a ',a.min())
print('how axis=1 works: ',b.max(axis=1))
print('how cumsum and axis=1 works: ',b.cumsum(axis=1))

[[0 1 2 3]
 [4 5 6 7]]
Sum of all a is  6
how axis=0 works:  [ 4  6  8 10]
min of a  0
how axis=1 works:  [3 7]
how cumsum and axis=1 works:  [[ 0  1  3  6]
 [ 4  9 15 22]]


NumPy allows you to calculate only in a **selected section** of your array via `slicing`.

In [48]:
a = np.arange(20)
print(a)
print(a[3:11])    # include index=3 to index=11-1=10
print(a[2:16:5])  # include index=2 to index=15 step_size=5
print(a[4::5])    # include index=4 to end step_size=5

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3  4  5  6  7  8  9 10]
[ 2  7 12]
[ 4  9 14 19]


In [50]:
a = np.arange(30).reshape(6,5)
print(a,'\n')
print(a[3:5])     # include row_index=3 to row_index=4
print(a[1::2])    # include row_index=1 to end, row_step=2
print(a[4:])      # include row_index=4 to end

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[[15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[[20 21 22 23 24]
 [25 26 27 28 29]]


In [53]:
print(a[0:5, 1:3])     # row_index: 0-4, column_index: 1-2
print(a[1:4, 1:4])     # row_index: 1-3, column_index: 1-3
print(a[0:5, 1::3])    # row_index: 0-4, column_index: 1 to end, column_step=3

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 1  4]
 [ 6  9]
 [11 14]
 [16 19]
 [21 24]]


In [54]:
size = np.array([['S','M','L','XL'],[28,30,32,34],[37,39,42,45]])
print(size)
chubby_customer = size[:,2:]   # include every row, column_index: 2 to end
print(chubby_customer)

[['S' 'M' 'L' 'XL']
 ['28' '30' '32' '34']
 ['37' '39' '42' '45']]
[['L' 'XL']
 ['32' '34']
 ['42' '45']]


if you would like to access
each individual value in the array, you need to use `flat` attribute

In [57]:
for row in a:
    print(row)
for element in a.flat:
    print(element, end=" ")

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 

In [60]:
# NumPy also has other class for scientific calculation, such as Matrix
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[1,3,5],[7,9,11],[13,15,17]])
print(a)
print(b)
print(a.transpose())
print(a*b)
print(np.dot(a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 54  66  78]
 [117 147 177]
 [180 228 276]]
[[ 54  66  78]
 [117 147 177]
 [180 228 276]]
